### ISSUE TITLE
Basic shared API snippet doesn't work in Excel

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-snippets#110]
The Excel snippet "Basic API Call (Office 2013)" throws "Invalid API call in the current context" when I have some (or all) text in a cell selected. Same error if I have the cell selected.

**Comment by kbrandl** [comment]
@Rick-Kirkham -- according to Michael Z., this behavior is by design.  i.e., the `getSelectedDataAsync` method will always throw an error if you're in *edit mode*.  It is certainly unfortunate that the error message "Invalid API call in the current context" isn't very helpful/informative. FWIW, a comparable call using the 2016 API (workbook.getSelectedRange) throws a much more helpful error:  "InvalidOperationInCellEditMode: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again."

**Comment by Rick-Kirkham** [comment]
Let's add some text to the page explaining what the user needs to do: 
1. Enter some text in a cell.
2. Select the cell, but do not select any text in it and be sure there is no blinking edit cursor in the cell.
3. Click the Run button. 
You can assign to me if you want.

**Comment by kbrandl** [comment]
@Rick-Kirkham -- sounds good.  I'll plan to include this update along with some other minor Script Lab snippet updates that I'll be working on soon.
