### ISSUE TITLE
Request for another Fabric example

### ISSUE THREAD

**Issue by deinspanjer** [OfficeDev/office-js-snippets#127]
I've looked through the `Fabric JS - Using form data` word sample a few times, but I'm having a real hard time merging the concepts there with the documentation and snippets found on the Fabric site ( https://developer.microsoft.com/en-us/fabric#/components/list ).  Would be great to get something with a bit more focus on how to create UI elements properly in Script Lab and use them.  Especially noting how it might be different from creating the component and using it in a standard office-js React add-in.

**Comment by deinspanjer** [comment]
Maybe part of my problem was that there doesn't actually seem to be any React in Script Lab at the moment.

I did find some docs and put together the following partially working snippet:
https://gist.github.com/deinspanjer/2f66e023b056cd5cf97b267209ea57e5

What I want to do with it is the following:
* Clickable names to allow easy organization and jumping to a sheet
* Multi-select with an option to hide or unhide groups of them
* Pay attention to the color coding of sheets, either for organization, or just to show and set it in the add-in UI

**Comment by kbrandl** [comment]
@deinspanjer -- thanks for reaching out about this.  Script Lab does not currently support React, and as far as I'm aware, there are no near term plans to add support for React.  I'm not entirely sure whether or not it would be useful for your scenario, but it looks like CodeSandbox (https://codesandbox.io/) may be an online code editor that you could use as a playground (instead of using Script Lab) to develop the type of snippets that you've described (it supports adding dependencies). Please note that CodeSandbox is not a Microsoft product and I have no firsthand experience using it (so this is not a formal endorsement, but rather, merely a suggestion of something you might consider looking into).

**Comment by deinspanjer** [comment]
@kbrandl That is okay.  I've been doing pretty well with building upon the example of fabric usage.  React was just the path I mistakenly headed down while reading introductions to the Office JS API in general.  I'll stick with Script Lab for now, and if I get a little spare time, I'd like to contribute a version of that gist as a further example of using fabric in Excel.

**Comment by kbrandl** [comment]
Thanks for the update, @deinspanjer.  Glad to hear that you're making progress and we look forward to your potential contribution here in the days ahead.
