### ISSUE TITLE
Remove many of the `console.log`-s and replace with OfficeHelpers.UI.notify

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js-snippets#28]
Example: dates snippet, when doing a "get"

**Comment by Zlatkovsky** [comment]
I only did for the handful of snippets I touched, but not for the vast majority of them (including the other hosts)

**Comment by kbrandl** [comment]
@AlexJerabek "OfficeHelpers" is publicly available -- any user can get use it by including the [@microsoft/office-js-helpers](https://www.npmjs.com/package/@microsoft/office-js-helpers) package in their project (source repo in GitHub is [OfficeDev/office-js-helpers](https://github.com/OfficeDev/office-js-helpers)).  In Script Lab, a snippet gains access to it by virtue of including it within the list of **Libraries** that the snippet specifies.

That said though, I tend to agree with you -- i.e., I prefer using `console.log()` over using `OfficeHelpers.UI.notify` for a few reasons:
- Like you, I have trouble noticing messages that `OfficeHelpers.UI.notify` displays, since it overlays directly over top of task pane and doesn't have any visual features that make it stand out.
- You can only display a single `OfficeHelpers.UI.notify` message at a time; each message overwrites the last (while `console.log` allows you to see the full list of messages that've been written until if/when you clear the console -- more effective for seeing the flow of what's occurred, which is what developers are usually most interested in).
- If a developer copies a function out of Script Lab into their add-in project and does not also include the reference to the **office-js-helpers** package, they'll get an error (if the function uses `OfficeHelpers`).

There are arguments to be made *for* using `OfficeHelpers` as well, but personally I prefer `console.log`...just my 2 cents.

**Comment by Zlatkovsky** [comment]
That's fine, I think you can close the issue and leave things be.
The original concern was that for a lot of people, I saw that they minimize Firebug once, and thus don't see any console output.  However, in the reworked version of Script Lab, we will have our own console component (for accessibility reasons, among others), and so there we can just always make sure to pop it open if output comes out.   So console.log is fine.
Feel free to close as "won't fix"
