### ISSUE TITLE
Color Wheel "Just for fun" sample has errors

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js-snippets#311]
This sample doesn't compile (extra `}`) and doesn't behave as expected (the wheel doesn't spin).

**Comment by AlexJerabek** [comment]
It looks like setting the fill color of one point on the pie chart sets them all. Here's a demo of what I believe to be an office-js bug: https://gist.github.com/AlexJerabek/88584a1296c9bc0e33a9406cc32522ab

**Comment by AlexJerabek** [comment]
Checking with @Zlatkovsky that I'm interpreting the behavior of that snippet and method correctly. If so and this is a product bug, I'll transfer the issue to office-js.

**Comment by Zlatkovsky** [comment]
The extra "}" should obviously be removed from the sample.  It must have snuck in at some point, because the sample did compile back in the day.

Just looked through the history, looks like it was your commit from 4 months ago that introduced it:  https://github.com/OfficeDev/office-js-snippets/commit/991f2a38081fa51873affa0a646920c15f94a928#diff-7b97a8604a8df2e7724bacdb83bd4272

![image](https://user-images.githubusercontent.com/2230453/59978239-3eeb9800-958f-11e9-9f3a-dc4187a7e2c9.png)

... But for the bigger issue:  yes, you are right, the Chart API seems to have a regression in the actual office-js code.  Your snippet demonstrates it well.  I suggest you file a separate bug on office-js using your snippet.  It would be good to understand how automation didn't catch it, either.

**Comment by AlexJerabek** [comment]
Thanks @Zlatkovsky. The extra bracket was fixed as part of #312. I'll file the bigger Chart issue on office-js.
