### ISSUE TITLE
Unable to call fetch

### ISSUE THREAD

**Issue by chicagocomputerclasses** [OfficeDev/office-js-snippets#332]
I'm unable to call fetch and can't find documentation regarding web calls. I assume you have to import fetch in libraries but I can't figure out how.

**Comment by kbrandl** [comment]
@chicagocomputerclasses sorry to hear that you're having trouble with fetch. Since using fetch to make web calls relates to general web development (and isn't specifically tied to Office Add-ins), I'd suggest you check out the [Using Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) article within the MDN docs. If you can't get things to work after reading that documentation, I'd suggest that you post to Stack Overflow and tag your question with [fetch-api](https://stackoverflow.com/questions/tagged/fetch-api). You might also want to search already-existing questions/answers within that tag on Stack Overflow, as it's quite possible that the information you need already exists there.

**Comment by chicagocomputerclasses** [comment]
Hi kbrandi, thanks, but I use fetch all the time for general web development and Node JS.

The question is whether fetch is included within Script Lab plugin environment, because it returns undefined and if it's not how can it be added as a library.

I can't find Script Lab documentation about adding libraries. Can you point me to it?

**Comment by kbrandl** [comment]
@chicagocomputerclasses thanks for clarifying your ask; I'll re-open this issue and see what I can find out about this.

**Comment by kbrandl** [comment]
Actually, @AlexJerabek has some info to share about this, so I'm going to hand this off to him. Thanks @AlexJerabek!

**Comment by AlexJerabek** [comment]
Hi @chicagocomputerclasses,
@Zlatkovsky created a gist using fetch in Script Lab: https://gist.github.com/Zlatkovsky/522183067333a47d8ec4f7e8a4823c57 
It's a custom function that queries a stock ticker.

He notes that on IE11 you need to include the “fetch” polyfill.  “whatwg-fetch” is a common one:  https://github.com/github/fetch

Let me know if that helps unblock you.

**Comment by AlexJerabek** [comment]
Also, for context, older versions Office Add-ins use IE11 to display their iFrames. Here's an article with that information: https://docs.microsoft.com/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

**Comment by AlexJerabek** [comment]
Tagging @ElizabethSamuel-MSFT for awareness about Script Lab doc needs.

**Comment by AlexJerabek** [comment]
Hi @chicagocomputerclasses,

Did the provided information unblock you using fetch with Script Lab? We're looking to improve our [Script Lab documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) and will figure out how to best address this documentation gap. 

I'm going to close the issue, but please respond to the thread if you need something else and I'll happily reopen it. Thanks!

**Comment by chicagocomputerclasses** [comment]
"Also, for context, older versions of Office Add-ins use the IE11 browser engine"

Sorry for not replying earlier but this has resolved my problem. I wasn't aware of this. After running window.navigator.userAgent I've discovered that it was in fact using Internet Explorer. I'm still not entirely sure why, because the system was windows 10 and office was 365 with newest updates. Anyhow, using a polyfill fixed this issue.

Thank You!
